/***********************************************************
 * File generated by the HALCON-Compiler hcomp version 12.0
 * Usage: Interface to C++
 *
 * Software by: MVTec Software GmbH, www.mvtec.com
 ***********************************************************/


#ifndef HCPP_HSTEREOMODEL
#define HCPP_HSTEREOMODEL

namespace HalconCpp
{

// Represents an instance of a stereo model.
class LIntExport HStereoModel : public HToolBase
{

public:

  // Create an uninitialized instance
  HStereoModel():HToolBase() {}

  // Copy constructor
  HStereoModel(const HStereoModel& source) : HToolBase(source) {}

  // Create HStereoModel from handle, taking ownership
  explicit HStereoModel(Hlong handle);

  // Set new handle, taking ownership
  void SetHandle(Hlong handle);



/*****************************************************************************
 * Operator-based class constructors
 *****************************************************************************/

  // create_stereo_model: Create a HALCON stereo model.
  explicit HStereoModel(const HCameraSetupModel& CameraSetupModelID, const HString& Method, const HTuple& GenParamName, const HTuple& GenParamValue);

  // create_stereo_model: Create a HALCON stereo model.
  explicit HStereoModel(const HCameraSetupModel& CameraSetupModelID, const HString& Method, const HString& GenParamName, const HTuple& GenParamValue);

  // create_stereo_model: Create a HALCON stereo model.
  explicit HStereoModel(const HCameraSetupModel& CameraSetupModelID, const char* Method, const char* GenParamName, const HTuple& GenParamValue);




  /***************************************************************************
   * Operators                                                               *
   ***************************************************************************/

  // Reconstruct 3D points from calibrated multi-view stereo images.
  void ReconstructPointsStereo(const HTuple& Row, const HTuple& Column, const HTuple& CovIP, Hlong CameraIdx, Hlong PointIdx, HTuple* X, HTuple* Y, HTuple* Z, HTuple* CovWP, HTuple* PointIdxOut) const;

  // Reconstruct 3D points from calibrated multi-view stereo images.
  void ReconstructPointsStereo(double Row, double Column, const HTuple& CovIP, Hlong CameraIdx, Hlong PointIdx, double* X, double* Y, double* Z, double* CovWP, Hlong* PointIdxOut) const;

  // Reconstruct surface from calibrated multi-view stereo images.
  HObjectModel3D ReconstructSurfaceStereo(const HImage& Images) const;

  // Get intermediate iconic results of a stereo reconstruction.
  HObject GetStereoModelObject(const HTuple& PairIndex, const HString& ObjectName) const;

  // Get intermediate iconic results of a stereo reconstruction.
  HObject GetStereoModelObject(Hlong PairIndex, const HString& ObjectName) const;

  // Get intermediate iconic results of a stereo reconstruction.
  HObject GetStereoModelObject(Hlong PairIndex, const char* ObjectName) const;

  // Return the list of image pairs set in a stereo model.
  HTuple GetStereoModelImagePairs(HTuple* To) const;

  // Specify image pairs to be used for surface stereo reconstruction.
  void SetStereoModelImagePairs(const HTuple& From, const HTuple& To) const;

  // Get stereo model parameters.
  HTuple GetStereoModelParam(const HTuple& ParamName) const;

  // Get stereo model parameters.
  HTuple GetStereoModelParam(const HString& ParamName) const;

  // Get stereo model parameters.
  HTuple GetStereoModelParam(const char* ParamName) const;

  // Set stereo model parameters.
  void SetStereoModelParam(const HTuple& ParamName, const HTuple& ParamValue) const;

  // Set stereo model parameters.
  void SetStereoModelParam(const HString& ParamName, const HTuple& ParamValue) const;

  // Set stereo model parameters.
  void SetStereoModelParam(const char* ParamName, const HTuple& ParamValue) const;

  // Create a HALCON stereo model.
  void CreateStereoModel(const HCameraSetupModel& CameraSetupModelID, const HString& Method, const HTuple& GenParamName, const HTuple& GenParamValue);

  // Create a HALCON stereo model.
  void CreateStereoModel(const HCameraSetupModel& CameraSetupModelID, const HString& Method, const HString& GenParamName, const HTuple& GenParamValue);

  // Create a HALCON stereo model.
  void CreateStereoModel(const HCameraSetupModel& CameraSetupModelID, const char* Method, const char* GenParamName, const HTuple& GenParamValue);

};

// forward declarations and types for internal array implementation

template<class T> class HSmartPtr;
template<class T> class HToolArrayRef;

typedef HToolArrayRef<HStereoModel> HStereoModelArrayRef;
typedef HSmartPtr< HStereoModelArrayRef > HStereoModelArrayPtr;


// Represents multiple tool instances
class LIntExport HStereoModelArray : public HToolArray
{

public:

  // Create empty array
  HStereoModelArray();

  // Create array from native array of tool instances
  HStereoModelArray(HStereoModel* classes, Hlong length);

  // Copy constructor
  HStereoModelArray(const HStereoModelArray &tool_array);

  // Destructor
  virtual ~HStereoModelArray();

  // Assignment operator
  HStereoModelArray &operator=(const HStereoModelArray &tool_array);

  // Clears array and all tool instances
  virtual void Clear();

  // Get array of native tool instances
  const HStereoModel* Tools() const;

  // Get number of tools
  virtual Hlong Length() const;

  // Create tool array from tuple of handles
  virtual void SetFromTuple(const HTuple& handles);

  // Get tuple of handles for tool array
  virtual HTuple ConvertToTuple() const;

protected:

// Smart pointer to internal data container
   HStereoModelArrayPtr *mArrayPtr;
};

}

#endif
